services:
  user_service: 
    build: ./services/user_service
    volumes:
      - ./services/user_service/app:/app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+asyncmy://${DB_USER}:${DB_PASSWORD}@user_db:3306/user_db
      - REDIS_URL=${REDIS_URL}
    depends_on:
      user_db:
        condition: service_healthy
      redis_db:
        condition: service_started