#./docker-compose.yml
# 도커 컴포즈 파일 버전 지정
version: '3.8'

# 서비스(컨테이너 하나)를 정의하는 부분
# 이름이 fastapi_app
services:
  #db 서비스 이름
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #root pw
      MYSQL_DATABASE: ${MYSQL_DATABASE} #database name
    volumes:
      - mysql_data:/var/lib/mysql # 저장위치
    ports:
      - "3307:3306" # 포트번호
       
  fastapi_app:
    # 이미지 직접 빌드
    build:
      # 현재 디렉토리에서 빌드할 거라는 뜻
      context: .
      # Dockerfile 파일을 사용해서 빌드
      dockerfile: Dockerfile
    # 포트 연결
    # localhost:8000으로 접속하면 컨테이너의 FastAPI로 연결됨
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    # 볼륨 (폴더 공유) 설정
    # 내 컴퓨터의 ./app 폴더와 컨테이너의 /app 폴더를 연결
    # 내 파일을 수정하면 컨테이너에서도 실시간으로 반영됨
    volumes:
      - ./app:/app
    # 컨테이너가 시작할 때 실행할 명령어를 지정
    # FastAPI 서버를 uvicorn으로 실행하고,
    # --reload 옵션이 있어서, 코드를 수정하면 서버가 자동으로 재시작됨(개발 모드)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data: